kyc/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from kyc import views



app_name = 'kyc'

urlpatterns = [
    path('kyc_form/', views.SubmitKycTemplateView.as_view(),name = 'submited'),
    path('kyc',views.KycFormCreateView.as_view(),name='kyc_form'),
    path('wallet_balance',views.wallet_balance,name='wallet_balance'),

    
]

profiles/urls.py
from django.conf.urls import url
from django.urls import path
from profiles import views



app_name = 'profiles'

urlpatterns = [
    path('profile',views.ProfileUpdateView.as_view(),name='profile')
]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Dashboard.as_view(),name = 'dashboard'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complete'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('kyc/', include('kyc.urls',namespace = 'kyc')),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

profiles/models.py
from django.contrib import auth
from django.urls import reverse
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from django_countries.fields import CountryField
# from phonenumber_field.modelfields import PhoneNumberField
# from src.utils import profile_unique_slug_generator
# from django.db.models.signals import pre_save
# Create your models here.
class UserProfile(models.Model):

    # personal info 
    user = models.OneToOneField(User,related_name='userprofile', on_delete=models.CASCADE)
    avatar = models.ImageField(("displays"), upload_to='displays', height_field=None, width_field=None, max_length=None,default ='default.jpeg')
    create_date = models.DateTimeField(default = timezone.now)
    Gender = (
    ('male','Male'),
    ('female','Female'),
    ('others','Others'),
    )
    Cards = (
    ('silver','Silver'),
    ('gold','Gold'),
    ('Prepaid','Prepaid'),
    )
    age = models.PositiveIntegerField(("age"),null=True,blank=True)
    first_name = models.CharField(("first name"), max_length=50,null=True,blank=True)
    last_name = models.CharField(("last name"), max_length=50,null=True,blank=True)
    username = models.CharField(("username"), max_length=50,null=True)
    gender = models.CharField(("gender"), max_length=50,choices=Gender,null=True)
    email = models.EmailField(("email"),null=True, max_length=254)
    bio = models.CharField(("About you"), max_length=250,null=True,blank=True)
    website = models.URLField(("Website"), max_length=250,null=True,blank=True)
    card = models.CharField(("card"), max_length=50,choices=Cards,null=True,blank=True)
    
    # address info 
    country = CountryField()
    street_address = models.CharField(("street address"), max_length=70,null=True,blank=True)
    city = models.CharField(("city"), max_length=50,null=True)
    state = models.CharField(("state"), max_length=50,null=True)
    zip_code = models.CharField(("zip code"), max_length=50,null=True)

    # Buying info 

    one_click_purchasing = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)



    def __str__(self):
        return f'{self.user.username} UserProfile'
    

    def save(self,*args, **kwargs):
        self.username  = self.user.username
        self.email  = self.user.email

        super(UserProfile,self).save(*args, **kwargs) #it will take data and save it
    
    # def save_again(self,*args, **kwargs):
    #     if self.username:
    #         self.username  = self.user.username
    #     if self.age:
    #         self.age = self.user.age
    #     if self.gender:
    #         self.gender  = self.user.gender
    #     if self.first_name:
    #         self.first_name  = self.user.first_name
    #     if self.last_name:
    #         self.last_name  = self.user.last_name
    #     super(UserProfile,self).save(*args, **kwargs)

        dp = Image.open(self.avatar.path) #storing avatar in varible
        if dp.height >300 or dp.width >300:
            output_size =(300,300) #set anysize you want
            dp.thumbnail(output_size) 
            dp.save(self.avatar.path) #after resing it save it in data base in place of uploaded once by user

    def get_absolute_url(self):
        return reverse("profiles:profile")

@receiver(post_save,sender=User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        print('created userobject')
    else:
        print('not created')

@receiver(post_save,sender=User)
def save_profile(sender,instance,**kwargs):
    instance.userprofile.save()


# def userprofile_pre_save_reciever(sender,instance,*args, **kwargs):
#     if not instance.slug:
#         instance.slug = profile_unique_slug_generator(instance)
# pre_save.connect(userprofile_pre_save_reciever,UserProfile)
    

profiles/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.core import validators
from profiles.models import UserProfile
from django.core.mail import send_mail
from datetime import datetime
from django.core import validators
from django.contrib import messages
from django.core.exceptions import ValidationError
from django_countries.fields import CountryField
from django_countries.widgets import CountrySelectWidget
# from phonenumber_field.widgets import PhoneNumberPrefixWidget

class UserProfileForm(forms.ModelForm):
    
    class Meta:
        model = UserProfile
        fields = ("avatar","username","first_name","last_name","age","gender","country","card","email","bio","street_address","city","state","zip_code")
        # exclude = (,)
        # fields = ("avatar",)
        Gender = (
            ('male','Male'),
            ('female','Female'),
            ('others','Others'),
            )
        
        Cards = (
        ('silver','Silver'),
        ('gold','Gold'),
        ('Prepaid','Prepaid'),
        )
                
        widgets ={
            # 'avatar': forms.ImageField(attrs={'class':'form-control'}, required=True),
            'first_name' : forms.TextInput(attrs={'class':'form-control'}),
            'last_name' : forms.TextInput(attrs={'class':'form-control'}),
            'age' : forms.TextInput(attrs={'class':'form-control','title':'Age should be more then 18'}),
            'gender' : forms.Select(choices=Gender,attrs={'class': 'form-control'}),
            'country': CountrySelectWidget(),
            # 'phone': PhoneNumberPrefixWidget(),
            'username' : forms.TextInput(attrs={'class': 'form-control','id':'disabledInput'}),
            'email' : forms.TextInput(attrs={'class': 'form-control','id':'eMail'}),
            'street_address' : forms.TextInput(attrs={'class': 'form-control','id':'Street'}),
            'city' : forms.TextInput(attrs={'class': 'form-control','id':'ciTy'}),
            'state' : forms.TextInput(attrs={'class': 'form-control','id':'sTate'}),
            'zip_code' : forms.TextInput(attrs={'class': 'form-control','id':'zIp'}),
            'bio' : forms.TextInput(attrs={'class': 'form-control','id':'bio'}),
            'card' : forms.Select(choices=Cards,attrs={'class': 'form-control'}),

            # 'website' : forms.TextInput(attrs={'class': 'form-control','id':'website'}),
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request', None)
        super(UserProfileForm, self).__init__(*args, **kwargs)
        instance = getattr(self, 'instance', None)
        if instance and instance.pk:
            self.fields['username'].widget.attrs['readonly'] = True
            self.fields['email'].widget.attrs['readonly'] = True
            self.fields['card'].widget.attrs['disabled'] = True
        
    def clean_age(self):
        age = self.cleaned_data["age"]
        # print(age,'hm here')
        if age is not None:
            if age < 18:
                print(age,'hm here')
                raise forms.ValidationError("You age should be 18 plus")
            return age
    
    # def clean_phone(self):
    #     phone = self.cleaned_data["phone"]
    #     print(phone,'phone i am ')
        
    

       
            

profiles/views.py
from django.shortcuts import render
from . forms import UserProfileForm
from . models import UserProfile
from kyc.models import KycModel
from django.contrib.auth.mixins import LoginRequiredMixin
# from shoprequests.models import ShopRequest
from django.views.generic import UpdateView
# Create your views here.

class ProfileUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/accounts/login/'
    refirect_field_name ='profiles:profile'
    template_name = 'profiles/profile_update.html'
    form_class = UserProfileForm
    model = UserProfile

    def get_object(self, *args, **kwargs):
        return self.request.user.userprofile
    
    def get_form_kwargs(self, *args, **kwargs):
        form_kwargs = super().get_form_kwargs(*args, **kwargs)
        form_kwargs['request'] = self.request
        return form_kwargs
    
    def get_context_data(self, *args, **kwargs):
        context = super(ProfileUpdateView, self).get_context_data(*args, **kwargs)
        update_form = UserProfileForm(instance = self.request.user.userprofile)
        context['form'] = update_form
        try :
            kyc = KycModel.objects.get(owner=self.request.user)
        except KycModel.DoesNotExist:
             kyc = False
        print(kyc,"kyc")
        context["kyc"] = kyc
        return context
    
    def form_valid(self, form):
        print("im coming from views")
        if self.request == 'POST':
            # phone= form.cleaned_data['phone']
            # print("im coming from views",phone)
            form.save()
        return super().form_valid(form)

profiles/templates/profiles/profile_update.html
{% extends 'base.html' %}
{% load static %}
{% load bootstrap3 %}

{% block content %}
  {% include 'snippets/dashboard_sidebar.html' with shop=shop %}


<div class="container">

{% for message in messages %}
    {% if message %}
            <div class="alert alert-danger container" style="textalign:center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×</button>
               {% comment %} <span class="glyphicon glyphicon-cross"></span> <strong>You're successfully registered</strong> {% endcomment %}
                {% comment %} <hr class="message-inner-separator"> {% endcomment %}
                <p>{{message}}</p>
            </div>
    {% endif %}
    {% endfor %}
<br><br>
 <style>
{% comment %} body {
    margin: 0;
    padding-top: 40px;
    color: #2e323c;
    background: #f5f6fa;
    position: relative;
    height: 100%;
} {% endcomment %}
.account-settings .user-profile {
    margin: 0 0 1rem 0;
    padding-bottom: 1rem;
    text-align: center;
}
.account-settings .user-profile .user-avatar {
    margin: 0 0 1rem 0;
	
}
.account-settings .user-profile .user-avatar img {
    width: 90px;
    height: 90px;
    -webkit-border-radius: 100px;
    -moz-border-radius: 100px;
    border-radius: 100px;
}
.account-settings .user-profile h5.user-name {
    margin: 0 0 0.5rem 0;
}
.account-settings .user-profile h6.user-email {
    margin: 0;
    font-size: 14px;
    font-weight: 400;
    color: #9fa8b9;
	padding: 1rem;
}
.account-settings .about {
    margin: 2rem 0 0 0;
    text-align: center;
}
.account-settings .about h5 {
    margin: 0 0 15px 0;
    color: #007ae1;
}
.account-settings .about p {
    font-size: 14px;
}
.form-control {
    border: 1px solid #cfd1d8;
    -webkit-border-radius: 2px;
    -moz-border-radius: 2px;
    border-radius: 2px;
    font-size: 14px;
    background: #ffffff;
    color: #2e323c;
}

.card {
    background: #ffffff;
    -webkit-border-radius: 5px;
    -moz-border-radius: 5px;
    border-radius: 5px;
    border: 0;
    margin-bottom: 1rem;
    padding:20px;
}
.detail_body{
	padding-right:60px;
}
.user_profile{
    text-align:center;
    font-weight:600;
    margin-top:-40px;
    border:2px solid black;
    
}
 </style>
<h1><p class="user_profile">USER PROFILE</p></h1>

<div class="container">

<div class="row gutters">
<div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
<div class="card h-100">
	<div class="card-body">
		<div class="account-settings">
			<div class="user-profile">
				<div class="user-avatar">
					<img src="{{request.user.userprofile.avatar.url}}" alt="{{user.username}}">
				</div>
				<h5 class="user-name">{{user.username}}</h5>
				<h6 class="user-email">{{user.email}}</h6>
				<p><strong>
				{% if request.user.userprofile.card and kyc.kyc_approve == "Approved"%}
						{{request.user.userprofile.card|capfirst}}
				{% endif %} 
				</strong></p>
				
			</div>
          
			<div class="about">
				<h5>About</h5>
				<p>{{user.userprofile.bio}}</p>
			</div>
		</div>
	</div>
</div>
</div>

<div class="col-xl-9 col-lg-8 col-md-12 col-sm-12 col-12 detail_body">

	<div class="card h-100">
		<form method="POST" enctype="multipart/form-data">{% csrf_token %}
			<div class="card-body">
				<div class="row gutters">
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						<h6 class="mb-2 text-primary">Personal Details</h6>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% comment %} <label>Image</label> {% endcomment %}
							{% bootstrap_field form.avatar %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% comment %} <label for="disabledInput">USERNAME</label> {% endcomment %}
							{% bootstrap_field form.username %}
						</div>
					</div> 
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
				
						{% if request.user.userprofile.card and kyc.kyc_approve == "Approved"%}
						{% bootstrap_field form.card %}
						{% endif %} 
							{% comment %} <label for="card">Website URL</label>
							<input type="url" class="form-control" id="website" placeholder="Website url"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.email %}
							{% comment %} <label for="eMail">Email</label>
							<input type="email" class="form-control" id="eMail" placeholder="Enter email ID"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.first_name %}
							{% comment %} <label for="id_first_name">First Name</label> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% comment %} <label for="id_last_name">Last Name</label> {% endcomment %}
							{% bootstrap_field form.last_name %}
						</div>
					</div>

					
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.bio %}
							{% comment %} <label for="fullName">Full Name</label>
							<input type="text" class="form-control" id="fullName" placeholder="Enter full name"> {% endcomment %}
						</div> 
					</div>
				
					
					{% comment %} <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.website %}
							<label for="website">Website URL</label>
							<input type="url" class="form-control" id="website" placeholder="Website url">
						</div>
					</div> {% endcomment %}
	
					
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% bootstrap_field form.age %}
						</div>
					</div>
					
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% comment %} <label for="id_gender">Gender</label> {% endcomment %}
							{% bootstrap_field form.gender %}
						</div>
					</div> 
					

				</div>
				<div class="row gutters">
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						<h6 class="mt-3 mb-2 text-primary">Address</h6>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.street_address %}
							{% comment %} <label for="Street">Street</label>
							<input type="name" class="form-control" id="Street" placeholder="Enter Street"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.city %}
							{% comment %} <label for="ciTy">City</label>
							<input type="name" class="form-control" id="ciTy" placeholder="Enter City"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.state %}
							{% comment %} <label for="sTate">State</label>
							<input type="text" class="form-control" id="sTate" placeholder="Enter State"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
						{% bootstrap_field form.zip_code %}
							{% comment %} <label for="zIp">Zip Code</label>
							<input type="text" class="form-control" id="zIp" placeholder="Zip Code"> {% endcomment %}
						</div>
					</div>
					<div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
						<div class="form-group">
							{% comment %} <label for="id_country">Country</label> {% endcomment %}
							{% bootstrap_field form.country %}
						</div>
					</div>
					
				</div>
				<div class="row gutters">
					<div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
						<div class="text-right">
							{% comment %} <button type="submit" id="submit" name="submit" class="btn btn-secondary">Cancel</button> {% endcomment %}
							<button type="submit" id="submit" name="submit" class="btn btn-primary">Update</button>
						</div>
					</div>
				</div>
			</div>
		</form>
	</div>

</div>
</div>


</div>
{% comment %} {% bootstrap_field form.username %} {% endcomment %}
  {% comment %} <img src="{{request.user.userprofile.avatar.url}}" class="img-resonsive img-circle" alt="..."></span> {% endcomment %}
     {% comment %} <form method="POST" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form form %}
    
     <button type="submit" class="btn btn-primary btn-block btn-flat">Save</button> 
    </form>   {% endcomment %}
</div>

{% endblock content %}