accounts/urls.py
from django.conf.urls import url
from django.urls import path
from accounts import views
from django.views import generic



app_name = 'accounts'

urlpatterns = [
    path('login/',views.CoustomLoginView.as_view(template_name='accounts/login.html'),name = 'login'),
    path('signup/',views.SignUp.as_view(),name='signup'),
    path('email_taken',views.email_taken,name="email_taken"),
    path('activate/<uidb64>/<token>/',views.ActivateAccount.as_view(), name='activate'),
    # path('email',generic.TemplateView.as_view(template_name='accounts/account_activation_email.html'))
]

kyc/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from kyc import views



app_name = 'kyc'

urlpatterns = [
    path('kyc_form/', views.SubmitKycTemplateView.as_view(),name = 'submited'),
    path('kyc',views.KycFormCreateView.as_view(),name='kyc_form'),
    path('wallet_balance',views.wallet_balance,name='wallet_balance'),

    
]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Dashboard.as_view(),name = 'dashboard'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complete'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('kyc/', include('kyc.urls',namespace = 'kyc')),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.urls import reverse
from django.db import models
from django.contrib import auth
# from django.db.models.signals import post_save
# from django.dispatch import receiver

from django.utils.translation import gettext_lazy as _
# Create your models here.

class User(auth.models.User,auth.models.PermissionsMixin):

    def __str__(self):
        return "@{}".format(self.username)

profiles/models.py
from django.contrib import auth
from django.urls import reverse
from PIL import Image
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db import models
from django.utils import timezone
from django_countries.fields import CountryField
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator

from django.contrib.auth.models import AbstractBaseUser
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.contrib.auth.models import User
from django_countries.fields import CountryField
# from phonenumber_field.modelfields import PhoneNumberField
# from src.utils import profile_unique_slug_generator
# from django.db.models.signals import pre_save
# Create your models here.
class UserProfile(models.Model):

    # personal info 
    user = models.OneToOneField(User,related_name='userprofile', on_delete=models.CASCADE)
    avatar = models.ImageField(("displays"), upload_to='displays', height_field=None, width_field=None, max_length=None,default ='default.jpeg')
    create_date = models.DateTimeField(default = timezone.now)
    Gender = (
    ('male','Male'),
    ('female','Female'),
    ('others','Others'),
    )
    Cards = (
    ('silver','Silver'),
    ('gold','Gold'),
    ('Prepaid','Prepaid'),
    )
    age = models.PositiveIntegerField(("age"),null=True,blank=True)
    first_name = models.CharField(("first name"), max_length=50,null=True,blank=True)
    last_name = models.CharField(("last name"), max_length=50,null=True,blank=True)
    username = models.CharField(("username"), max_length=50,null=True)
    gender = models.CharField(("gender"), max_length=50,choices=Gender,null=True)
    email = models.EmailField(("email"),null=True, max_length=254)
    bio = models.CharField(("About you"), max_length=250,null=True,blank=True)
    website = models.URLField(("Website"), max_length=250,null=True,blank=True)
    card = models.CharField(("card"), max_length=50,choices=Cards,null=True,blank=True)
    
    # address info 
    country = CountryField()
    street_address = models.CharField(("street address"), max_length=70,null=True,blank=True)
    city = models.CharField(("city"), max_length=50,null=True)
    state = models.CharField(("state"), max_length=50,null=True)
    zip_code = models.CharField(("zip code"), max_length=50,null=True)

    # Buying info 

    one_click_purchasing = models.BooleanField(default=False)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)



    def __str__(self):
        return f'{self.user.username} UserProfile'
    

    def save(self,*args, **kwargs):
        self.username  = self.user.username
        self.email  = self.user.email

        super(UserProfile,self).save(*args, **kwargs) #it will take data and save it
    
    # def save_again(self,*args, **kwargs):
    #     if self.username:
    #         self.username  = self.user.username
    #     if self.age:
    #         self.age = self.user.age
    #     if self.gender:
    #         self.gender  = self.user.gender
    #     if self.first_name:
    #         self.first_name  = self.user.first_name
    #     if self.last_name:
    #         self.last_name  = self.user.last_name
    #     super(UserProfile,self).save(*args, **kwargs)

        dp = Image.open(self.avatar.path) #storing avatar in varible
        if dp.height >300 or dp.width >300:
            output_size =(300,300) #set anysize you want
            dp.thumbnail(output_size) 
            dp.save(self.avatar.path) #after resing it save it in data base in place of uploaded once by user

    def get_absolute_url(self):
        return reverse("profiles:profile")

@receiver(post_save,sender=User)
def create_profile(sender,instance,created,**kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        print('created userobject')
    else:
        print('not created')

@receiver(post_save,sender=User)
def save_profile(sender,instance,**kwargs):
    instance.userprofile.save()


# def userprofile_pre_save_reciever(sender,instance,*args, **kwargs):
#     if not instance.slug:
#         instance.slug = profile_unique_slug_generator(instance)
# pre_save.connect(userprofile_pre_save_reciever,UserProfile)
    

accounts/forms.py
from django.contrib.auth import get_user_model
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.forms import AuthenticationForm
from django.utils.translation import gettext, gettext_lazy as _
from django.core.exceptions import ValidationError
from django.contrib.auth import authenticate, login

      
class CustomLoginForm(AuthenticationForm):

    username = forms.CharField(label='Email / Username')


    def __init__(self, *args, **kwargs):
        super(CustomLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = ('Email / Username')
        self.fields['username'].label = ''
        self.fields['password'].widget.attrs['placeholder'] = ('Password')
        self.fields['password'].label = ''

    def clean_username(self):
        username = self.cleaned_data["username"]
        if User.objects.filter(username__iexact=username).exists() or User.objects.filter(email__iexact=username).exists() :
            pass
        else:
            raise forms.ValidationError("Email / Username not register")
        return username




class UserCreateForm(UserCreationForm):

    class Meta:
        
        model = User
        fields = ["username","email","password1","password2"]
        
        widgets ={
            'email' : forms.TextInput(attrs={'class':'control-flow'}),
        
        }
        
    def clean_email(self):
        email = self.cleaned_data["email"]
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("Email already exist")
        return email
        
    def __init__(self,*args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = ('Enter your username')
        self.fields['username'].label = ''
        self.fields['email'].widget.attrs['placeholder'] = ('Enter your email')
        self.fields['email'].label = ''
        self.fields['password1'].widget.attrs['placeholder'] = ('Password')
        self.fields['password1'].label = ''
        self.fields['password2'].widget.attrs['placeholder'] = ('Confirm Password')
        self.fields['password2'].label = ''

        for fieldname in ['username', 'password1', 'password2']:
            self.fields[fieldname].help_text = None





  

accounts/views.py
from django.shortcuts import render,redirect
from django.urls import reverse_lazy
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from .forms import UserCreateForm
from django.views.generic import CreateView,TemplateView,View
from . import forms
from source import settings
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView
# email 
from django.contrib import messages
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes
from django.utils.http import urlsafe_base64_encode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth import login
from django.utils.encoding import force_text
from django.utils.http import urlsafe_base64_decode
from django.core.mail import send_mail
from django.contrib import messages
from django.template import loader
from . import forms
from django.contrib.auth import login as auth_login
from django.contrib.auth.models import User
from django.http import HttpResponse,JsonResponse
# Create your views here.


def email_taken(request):
    
    email = request.GET.get('search')
    print('imi im ',email)
    msg = "Valid"
    if User.objects.filter(email__iexact=email).exists():
        msg1 = "Email already exist"  
        msg = None
        return JsonResponse({'error1':msg1,'error':msg })
    return JsonResponse({'error':msg })

class SignUp(CreateView):
    form_class = UserCreateForm
    template_name = 'accounts/signup.html'
        
    def get(self, request, *args, **kwargs):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)
            user.is_active = False # Deactivate account till it is confirmed
            user.save()

            current_site = get_current_site(request)
            subject = 'Activate Your Dotescrow Account'
            html_message = loader.render_to_string('accounts/account_activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
            })
            user.email_user(subject,'message' ,fail_silently=True,html_message=html_message)
            messages.success(request, 'Please verify you email to activate you account.')
            return redirect('accounts:signup')

        return render(request, self.template_name, {'form': form})


class CoustomLoginView(LoginView):

    authentication_form = forms.CustomLoginForm
    
    # def get_form_kwargs(self, *args, **kwargs):
    #     form_kwargs = super().get_form_kwargs(*args, **kwargs)
    #     form_kwargs['request'] = self.request
    #     return form_kwargs
    

 
class ActivateAccount(View):

    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_text(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and account_activation_token.check_token(user, token):
            user.is_active = True
            print('user is active or not ',user.is_active)
            user.save()
            print('user is active or not ',user.is_active)
            messages.success(request, ('Your account have been confirmed.'))
            return redirect('accounts:login')
        else:
            messages.warning(request, ('The confirmation link was invalid, possibly because it has already been used.'))
            return redirect('accounts:signup')

accounts/templates/accounts/account_activation_email.html
{% autoescape off %}


<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <style type="text/css">
        @media screen {
            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 400;
                src: local('Lato Regular'), local('Lato-Regular'), url(https://fonts.gstatic.com/s/lato/v11/qIIYRU-oROkIk8vfvxw6QvesZW2xOQ-xsNqO47m55DA.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: normal;
                font-weight: 700;
                src: local('Lato Bold'), local('Lato-Bold'), url(https://fonts.gstatic.com/s/lato/v11/qdgUG4U09HnJwhYI-uK18wLUuEpTyoUstqEm5AMlJo4.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 400;
                src: local('Lato Italic'), local('Lato-Italic'), url(https://fonts.gstatic.com/s/lato/v11/RYyZNoeFgb0l7W3Vu1aSWOvvDin1pK8aKteLpeZ5c0A.woff) format('woff');
            }

            @font-face {
                font-family: 'Lato';
                font-style: italic;
                font-weight: 700;
                src: local('Lato Bold Italic'), local('Lato-BoldItalic'), url(https://fonts.gstatic.com/s/lato/v11/HkF_qI1x_noxlxhrhMQYELO3LdcAZYWl9Si6vvxL-qU.woff) format('woff');
            }
        }

        /* CLIENT-SPECIFIC STYLES */
        body,
        table,
        td,
        a {
            -webkit-text-size-adjust: 100%;
            -ms-text-size-adjust: 100%;
        }

        table,
        td {
            mso-table-lspace: 0pt;
            mso-table-rspace: 0pt;
        }

        img {
            -ms-interpolation-mode: bicubic;
        }

        /* RESET STYLES */
        img {
            border: 0;
            height: auto;
            line-height: 100%;
            outline: none;
            text-decoration: none;
        }

        table {
            border-collapse: collapse !important;
        }

        body {
            height: 100% !important;
            margin: 0 !important;
            padding: 0 !important;
            width: 100% !important;
        }

        /* iOS BLUE LINKS */
        a[x-apple-data-detectors] {
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        /* MOBILE STYLES */
        @media screen and (max-width:600px) {
            h1 {
                font-size: 32px !important;
                line-height: 32px !important;
            }
        }

        /* ANDROID CENTER FIX */
        div[style*="margin: 16px 0;"] {
            margin: 0 !important;
        }
    </style>
</head>

<body style="background-color: #f4f4f4; margin: 0 !important; padding: 0 !important;">
    <!-- HIDDEN PREHEADER TEXT -->
    <div style="display: none; font-size: 1px; color: #fefefe; line-height: 1px; font-family: 'Lato', Helvetica, Arial, sans-serif; max-height: 0px; max-width: 0px; opacity: 0; overflow: hidden;"> We're thrilled to have you here! Get ready to dive into your new account. </div>
    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- LOGO -->
        <tr>
            <td bgcolor="green" align="center">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="green" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                            <h1 style="font-size: 48px; font-weight: 400; margin: 2;">DOTEscrow</h1> <h4 style="font-size: 18px; font-weight: 400; margin: 2;">Hi {{ user.username }}</h4> <h1 style="font-size: 38px; font-weight: 400; margin: 2;">Welcome!</h1> <img src=" https://img.icons8.com/clouds/100/000000/handshake.png" width="125" height="120" style="display: block; border: 0px;" />
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="#f4f4f4" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 20px 30px 40px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">We're excited to have you get started. First, you need to confirm your account. Just press the button below.</p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left">
                            <table width="100%" border="0" cellspacing="0" cellpadding="0">
                                <tr>
                                    <td bgcolor="#ffffff" align="center" style="padding: 20px 30px 60px 30px;">
                                        <table border="0" cellspacing="0" cellpadding="0">
                                            <tr>
                                                <td align="center" style="border-radius: 3px;" bgcolor="green"><a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}" target="_blank" style="font-size: 20px; font-family: Helvetica, Arial, sans-serif; color: #ffffff; text-decoration: none; color: #ffffff; text-decoration: none; padding: 15px 25px; border-radius: 2px; border: 1px solid green; display: inline-block;">Confirm Account</a></td>
                                            </tr>
                                        </table>
                                    </td>
                                </tr>
                            </table>
                        </td>
                    </tr> <!-- COPY -->
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 0px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">If that doesn't work, copy and paste the following link in your browser:</p>
                        </td>
                    </tr> <!-- COPY -->
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 20px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;"><a href="http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}" target="_blank" style="color: green;">http://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}</a></p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 20px 30px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;"> if you have any questions,you can contact us--we're always happy to help out. </p>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="left" style="padding: 0px 30px 40px 30px; border-radius: 0px 0px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <p style="margin: 0;">Cheers,<br>FIT Team</p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
        {% comment %} <!-- <tr>
            <td bgcolor="#f4f4f4" align="center" style="padding: 30px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#FFECD1" align="center" style="padding: 30px 30px 30px 30px; border-radius: 4px 4px 4px 4px; color: #666666; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 18px; font-weight: 400; line-height: 25px;">
                            <h2 style="font-size: 20px; font-weight: 400; color: #111111; margin: 0;">Need more help?</h2>
                            <p style="margin: 0;"><a href="#" target="_blank" style="color: green;">We&rsquo;re here to help you out</a></p>
                        </td>
                    </tr>
                </table>
            </td>
        </tr> --> {% endcomment %}
    </table>
</body>

</html>


{% endautoescape %}

accounts/templates/accounts/password_reset_complete.html
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your password is successfully changed<p> 
<p><strong><a href="{% url 'accounts:login' %}">Log In</a></strong></p>
</div>

{% endblock  %}

accounts/templates/accounts/password_reset_confirm.html
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}

<div class='container' style='margin-top:18px'>
{% if validlink %}
<h1>Reset Password</h1>

<form class='accounts' method = 'POST'>
{% csrf_token %}
{% bootstrap_form form %}
<input type='submit' class='btn btn-success' value = 'Confirm'> 
{% else %}

<p class='alert alert-info' >The password reset link was invalid, possibly because it has already been used.  Please request a new password reset.</p>
<p><strong><a href ="{% url 'password_reset' %}">password reset.</strong></a></p>
{% endif %}
</div>
{% endblock  %}

accounts/templates/accounts/password_reset_done.html
{% load bootstrap3 %}
{% include 'snippets/dashboard_header.html' %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Check Your email to reset your password!<p> 
</div>
{% endblock  %}

accounts/templates/accounts/sent_confirm.html
{% load static %}
{% load bootstrap3 %}
{% block content %}
<div class='container' style='margin-top:20px'>
<p class='alert alert-info'>Your email is sent successfully. </p> 
</div>
{% endblock  %}

accounts/templates/accounts/signup.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html>
  <head>
    <meta charset="UTF-8">
    <title>DOTEScrow | Registration Page</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'dotescrow/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dotescrow/dist/css/AdminLTE.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- iCheck -->
    <link href="{% static 'dotescrow/plugins/iCheck/square/blue.css'%}" rel="stylesheet" type="text/css" />
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
  </head>
  <body class="register-page">

  <style>
    #msg_email_validation{
      color: red;
    }
  </style>
   {% for message in messages %}
    {% if message %}
            <div class="alert alert-success container" style="textalign:center">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">
                    ×</button>
               <span class="glyphicon glyphicon-ok"></span> <strong>You're successfully registered</strong>
                <hr class="message-inner-separator">
                <p>{{message}}</p>
            </div>
    {% endif %}
    {% endfor %}
    <div class="register-box">
      <div class="register-logo">
        <a href="{% static 'dotescrow/index2.html'%}"><b>Dot</b>ESCROW</a>
      </div>

      <div class="register-box-body">
        <p class="login-box-msg">Register a new membership</p>
        <form method="POST">{% csrf_token %}
       
          <div class="form-group has-feedback">
          {% bootstrap_field form.username %}
            <span class="glyphicon glyphicon-user form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
          {% bootstrap_field form.email %}
            <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
            <span id="msg_email_validation"></span>
          </div>
          
          <div class="form-group has-feedback">
            {% bootstrap_field form.password1 %}
            <span class="glyphicon glyphicon-lock form-control-feedback"></span>
          </div>
          <div class="form-group has-feedback">
            {% bootstrap_field form.password2 %}
            <span class="glyphicon glyphicon-log-in form-control-feedback"></span>
          </div>
          <div class="row">
            <div class="col-xs-8" style="margin-top:5px;">    
                       <a href="{% url 'accounts:login'%}" class="text-center">I already have a membership</a>         
            </div><!-- /.col -->
            <div class="col-xs-4">
              <button type="submit" class="btn btn-primary btn-block btn-flat">Register</button>
            </div><!-- /.col -->
          </div>
        </form>        

       
      </div><!-- /.form-box -->
    </div><!-- /.register-box -->

    <!-- jQuery 2.1.3 -->
    <script src="{% static 'dotescrow/plugins/jQuery/jQuery-2.1.3.min.js'%}"></script>
    <!-- Bootstrap 3.3.2 JS -->
    <script src="{% static 'dotescrow/bootstrap/js/bootstrap.min.js'%}" type="text/javascript"></script>
    <!-- iCheck -->
    <script src="{% static 'dotescrow/plugins/iCheck/icheck.min.js'%}" type="text/javascript"></script>
    <script>
      $(function () {
        $('input').iCheck({
          checkboxClass: 'icheckbox_square-blue',
          radioClass: 'iradio_square-blue',
          increaseArea: '20%' // optional
        });
      });

      
    
    

    </script>
  <script>

    var delayTimer;
    $('#id_email').keyup(function() {
      clearTimeout(delayTimer);
      $('#search_results').text('Loading...');
      delayTimer = setTimeout(function() {
          var text = $("#id_email").val();
          console.log(text,'search text');
          $.ajax({
            type: 'GET',
            url:'{% url "accounts:email_taken" %}',
            data:{
                "search":text
            },
            dataType:'json',
            success:function(json) {
            //document.getElementById("msg_email_validation").val() = json['error']
            
            msg = json['error']
            //console.log(msg)
            msg1 = json['error1']
            $('#msg_email_validation').text(msg1);
            console.log(msg1)
            }
          });
      },1000);
    });
  </script> 
  </body>
</html>