kyc/urls.py
from django.conf.urls import url
from django.urls import path
from django.contrib.auth import views as auth_views
from kyc import views



app_name = 'kyc'

urlpatterns = [
    path('kyc_form/', views.SubmitKycTemplateView.as_view(),name = 'submited'),
    path('kyc',views.KycFormCreateView.as_view(),name='kyc_form'),
    path('wallet_balance',views.wallet_balance,name='wallet_balance'),

    
]

profiles/urls.py
from django.conf.urls import url
from django.urls import path
from profiles import views



app_name = 'profiles'

urlpatterns = [
    path('profile',views.ProfileUpdateView.as_view(),name='profile')
]

source/urls.py
from django.urls import include, path
from django.contrib import admin
from . import views, settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.Dashboard.as_view(),name = 'dashboard'),

    #Auth django stuff 
    path('password_reset/',auth_views.PasswordResetView.as_view(template_name='accounts/password_reset.html'),name ='password_reset'),
    path('passsword_reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),name = 'password_reset_done'),
    path('reset/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),name = 'password_reset_confirm'),
    path('reset/done/',auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),name ='password_reset_complete'),
    path('logout/',auth_views.LogoutView.as_view(),name ='logout'),
    # Apps root 

    path('accounts/', include('accounts.urls',namespace = 'accounts')),
    path('profiles/', include('profiles.urls',namespace = 'profiles')),
    path('kyc/', include('kyc.urls',namespace = 'kyc')),



]
urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/snippets/cards.html

{% load static %}


{% comment %} before kyc form submit {% endcomment %}
{% if not kyc %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/debit-card.png"%}" alt="Card2"/>
                    <figcaption>
                        <div>
                            <h2 style="color:white;">Silver <span>Card</span></h2>
                            <p style="color:white;">Purchase <br>Now!</p>
                        </div>
                        <a href="{% url "kyc:kyc_form"%}">View more</a>
                    </figcaption>			
                </figure>
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/gold-card.png"%}" alt="Card3"/>
                    <figcaption>
                        <div>
                             <h2 style="color:white;">Gold <span>Card</span></h2>
                            <p style="color:white;">Purchase <br>Now!</p>
                        </div>
                        <a href="{% url "kyc:kyc_form"%}">View more</a>
                    </figcaption>			
                </figure>
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/platinum-card.png"%}" alt="Card1"/>
                    <figcaption>
                        <div>
                            <h2 style="color: white;">Prepaid <span>Card</span></h2>
                            <p style="color: white;">Purchase <br>Now!</p>
                        </div>
                        <a href="{% url "kyc:kyc_form"%}" style="color: white;">View more</a>
                    </figcaption>			
                </figure>
            </div>
        </div>


{% comment %} After kyc form submited before approval {% endcomment %}
    {% elif not kyc.kyc_approve  and kyc.card == "silver" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/debit-card.png"%}" alt="Card2"/>
                    <figcaption>
                        <div>
                            <h2 style="color:white;">Silver <span>Card</span></h2>
                            <p style="color:white;">Pending <br>You applied for silver card</p>
                        </div>
                        <a href="{% url "kyc:submited"%}">View more</a>
                    </figcaption>			
                </figure>
            </div>
        </div>
    {% elif not kyc.kyc_approve and kyc.card == "gold" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/gold-card.png"%}" alt="Card3"/>
                    <figcaption>
                        <div>
                             <h2 style="color:white;">Gold <span>Card</span></h2>
                             <p style="color:white;">Pending <br>You applied for Gold card</p>
                        </div>
                        <a href="{% url "kyc:submited"%}">View more</a>
                    </figcaption>				
                </figure>
            </div>
        </div>
    {% elif not kyc.kyc_approve and kyc.card == "Prepaid" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/platinum-card.png"%}" alt="Card1"/>
                    <figcaption>
                        <div>
                            <h2 style="color: white;">Prepaid <span>Card</span></h2>
                            <p style="color: white;"> Pending <br>You applied for Prepaid card</p>
                        </div>
                        <a href="{% url "kyc:submited"%}" style="color: white;">View more</a>
                    </figcaption>			
                </figure>
            </div>
        </div>

{% comment %} after kyc approval {% endcomment %}

    {% elif kyc.kyc_approve == "Approved" and kyc.card == "silver" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/debit-card.png"%}" alt="Card2"/>
                    <figcaption>
                        <div>
                            <h2 style="color:white;">Silver <span>Card</span></h2>
                            <p style="color:white;">Owner <br>You have Silver card</p>
                        </div>
                        {% comment %} <a href="{% url "kyc:submited"%}">View more</a> {% endcomment %}
                    </figcaption>			
                </figure>
            </div>
        </div>
    {% elif kyc.kyc_approve == "Approved" and kyc.card == "gold" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/gold-card.png"%}" alt="Card3"/>
                    <figcaption>
                        <div>
                            <h2 style="color:white;">Gold <span>Card</span></h2>
                             <p style="color:white;">Owner <br>You have Gold card</p>
                        </div>
                        {% comment %} <a href="{% url "kyc:submited"%}">View more</a> {% endcomment %}
                    </figcaption>				
                </figure>
            </div>
        </div>
    {% elif kyc.kyc_approve == "Approved" and kyc.card == "Prepaid" %}
        <div class="content">
            <div class="grid">
                <figure class="effect-lily">
                    <img class="img-responsive" src="{% static "dotescrow/cards/card-images/platinum-card.png"%}" alt="Card1"/>
                    <figcaption>
                        <div>
                            <h2 style="color: white;">Prepaid <span>Card</span></h2>
                            <p style="color: white;"> Owner <br>You have Prepaid card</p>
                        </div>
                        {% comment %} <a href="{% url "kyc:submited"%}" style="color: white;">View more</a> {% endcomment %}
                    </figcaption>			
                </figure>
            </div>
        </div>

{% endif %}

templates/snippets/dashboard_header.html
{% load static %}  
  
  <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- Bootstrap 3.3.2 -->
    <link href="{% static 'dotescrow/bootstrap/css/bootstrap.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- Font Awesome Icons -->
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="http://code.ionicframework.com/ionicons/2.0.0/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Morris chart -->
    <link href="{% static 'dotescrow/plugins/morris/morris.css'%}" rel="stylesheet" type="text/css" />
    <!-- jvectormap -->
    <link href="{% static 'dotescrow/plugins/jvectormap/jquery-jvectormap-1.2.2.css'%}" rel="stylesheet" type="text/css" />
    <!-- Daterange picker -->
    <link href="{% static 'dotescrow/plugins/daterangepicker/daterangepicker-bs3.css'%}" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="{% static 'dotescrow/dist/css/AdminLTE.min.css'%}" rel="stylesheet" type="text/css" />
    <!-- AdminLTE Skins. Choose a skin from the css/skins 
         folder instead of downloading all of them to reduce the load. -->
    <link href="{% static 'dotescrow/dist/css/skins/_all-skins.min.css'%}" rel="stylesheet" type="text/css" />
    
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->

templates/snippets/dashboard_nav.html
  {% load static %}
   <header class="main-header">
        <!-- Logo -->
        <a href="{% url 'dashboard' %}" class="logo"><b>Dot</b>escrow</a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
          <!-- Sidebar toggle button-->
          <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
          </a>
          <!-- Navbar Right Menu -->
          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <!-- Messages: style can be found in dropdown.less-->
              <li class="dropdown messages-menu">
                {% comment %} <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-envelope-o"></i>
                  <span class="label label-success">4</span>
                </a> {% endcomment %}
                <ul class="dropdown-menu">
                  {% comment %} <li class="header">You have 4 messages</li> {% endcomment %}
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- start message -->
                        <a href="#">
                          <div class="pull-left">
                            <img src="{% static 'dotescrow/dist/img/user2-160x160.jpg'%}" class="img-circle" alt="User Image"/>
                          </div>
                          <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li><!-- end message -->
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="{% static 'dotescrow/dist/img/user3-128x128.jpg'%}" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="{% static 'dotescrow/dist/img/user4-128x128.jpg'%}" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Sales Department
                            <small><i class="fa fa-clock-o"></i> Yesterday</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <div class="pull-left">
                            <img src="{% static 'dotescrow/dist/img/user4-128x128.jpg'%}" class="img-circle" alt="user image"/>
                          </div>
                          <h4>
                            Reviewers
                            <small><i class="fa fa-clock-o"></i> 2 days</small>
                          </h4>
                          <p>Why not buy a new awesome theme?</p>
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">See All Messages</a></li>
                </ul>
              </li>
              <!-- Notifications: style can be found in dropdown.less -->
              <li class="dropdown notifications-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  {% comment %} <i class="fa fa-bell-o"></i> {% endcomment %}
                  {% comment %} <span class="label label-warning">10</span> {% endcomment %}
                </a>
                <ul class="dropdown-menu">
                  {% comment %} <li class="header">You have 10 notifications</li> {% endcomment %}
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the page and may cause design problems
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-users text-red"></i> 5 new members joined
                        </a>
                      </li>

                      <li>
                        <a href="#">
                          <i class="fa fa-shopping-cart text-green"></i> 25 sales made
                        </a>
                      </li>
                      <li>
                        <a href="#">
                          <i class="fa fa-user text-red"></i> You changed your username
                        </a>
                      </li>
                    </ul>
                  </li>
                  <li class="footer"><a href="#">View all</a></li>
                </ul>
              </li>
              <!-- Tasks: style can be found in dropdown.less -->
              <li class="dropdown tasks-menu">
                {% comment %} <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-flag-o"></i>
                  <span class="label label-danger">9</span>
                </a> {% endcomment %}
                <ul class="dropdown-menu">
                  {% comment %} <li class="header">You have 9 tasks</li> {% endcomment %}
                  <li>
                    <!-- inner menu: contains the actual data -->
                    <ul class="menu">
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">20% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Create a nice theme
                            <small class="pull-right">40%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">40% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Some task I need to do
                            <small class="pull-right">60%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-red" style="width: 60%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">60% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                      <li><!-- Task item -->
                        <a href="#">
                          <h3>
                            Make beautiful transitions
                            <small class="pull-right">80%</small>
                          </h3>
                          <div class="progress xs">
                            <div class="progress-bar progress-bar-yellow" style="width: 80%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                              <span class="sr-only">80% Complete</span>
                            </div>
                          </div>
                        </a>
                      </li><!-- end task item -->
                    </ul>
                  </li>
                  <li class="footer">
                    <a href="#">View all tasks</a>
                  </li>
                </ul>
              </li>
              <!-- User Account: style can be found in dropdown.less -->
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <img src="{{request.user.userprofile.avatar.url}}" class="user-image" alt="User Image"/>
                  <span class="hidden-xs">{{request.user.username}}</span>
                </a>
                <ul class="dropdown-menu">
                  <!-- User image -->
                  <li class="user-header">
                    <img src="{{request.user.userprofile.avatar.url}}" class="img-circle" alt="User Image" />
                    <p>
                     {{request.user.username}}
                      <small>{{request.user.userprofile.create_date|date:"M d, Y" }}</small>
                    </p>
                  </li>

                  <!-- Menu Footer-->
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{% url 'profiles:profile'%}" class="btn btn-default btn-flat">Profile</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'logout'%}" class="btn btn-default btn-flat">Sign out</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>

templates/snippets/dashboard_sidebar.html
{% load static %}

<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
  <!-- sidebar: style can be found in sidebar.less -->
  <section class="sidebar">
    <!-- Sidebar user panel -->
    <div class="user-panel">
      <div class="pull-left image">
        <img src="{{request.user.userprofile.avatar.url}}" class="img-circle" alt="User Image" />
      </div>
      <div class="pull-left info">
        <p>{{request.user.username}}</p>
      </div>
    </div>
    <ul class="sidebar-menu">
      <li class="header">MAIN NAVIGATION</li>
      <li class="active treeview">
        <a href="{% url 'dashboard'%}">
          <i class="fa fa-dashboard"></i> <span>Dashboard</span>
        </a>
      </li>
      <li>
        <a href="{% url 'profiles:profile'%}">
          <i class="fa fa-pencil"></i> <span>Profile</span>
        </a>
      </li>
      <li>
       <a href="{% url 'kyc:kyc_form'%}">
          <i class="fa fa-calendar"></i> <span>KYC Form</span>
        </a> 
      </li>
    </ul>
  </section>
  <!-- /.sidebar -->
</aside>